# Generated by Django 5.2.13 on 2026-05-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='catalog_pro_sku_2c4c34_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='catalog_pro_name_f603c0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='catalog_pro_created_eee82f_idx'),
        ),
    ]
